import Head from "next/head";
import { Inter } from "next/font/google";
import Sidebar from "@/../components/Sidebar";
import Widgets from "@/../components/Widgets";
import Post from "@/../components/Post";
import InputModal from "@/../components/InputModal";
import {
  ChevronLeftIcon,
  HeartIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import { useRouter, Router } from "next/router";
import { useEffect, useState } from "react";
import { doc, onSnapshot } from "firebase/firestore";
import { db } from "@/firebase";

const inter = Inter({ subsets: ["latin"] });

export default function PostPage({ newsResults, randomUsersResults }) {
  const router = useRouter();
  const { id } = router.query;
  const [post, setPost] = useState();

  useEffect(
    () => onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot)),
    [db, id]
  );
  return (
    <div>
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icon" />
      </Head>

      <main className="mx-auto flex min-h-screen max-w-7xl">
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}
        <div className="max-w-xl flex-grow md:ml-[73px] lg:ml-[180px] xl:ml-[300px] xl:min-w-[576px]">
          <div className="sticky top-0 z-40 flex  bg-white/70 px-2 py-2 backdrop-blur-md dark:bg-black/70 sm:pb-5 sm:pt-7">
            <div
              onClick={() => router.push("/")}
              className="hoverEffect mr-2 flex h-10 w-10 items-center justify-center px-0"
            >
              <XMarkIcon className="h-8" />
            </div>
            {/* <div className="ml-auto flex h-8 w-8 items-center justify-center px-0">
              <button
                // onClick={signIn}
                className=" text-black dark:text-white"
              >
                <HeartIcon className="h-8" />
              </button>
            </div> */}
          </div>

          <Post id={id} post={post} />
        </div>

        {/* Widgets */}
        {post?.data()?.link && <Widgets mediaLink={post?.data()?.link} />}

        {/* Modal */}
        <InputModal />
      </main>
    </div>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());

  // who to follow section

  const randomUsersResults = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  ).then((res) => res.json());
  return {
    props: {
      newsResults,
      randomUsersResults,
    },
  };
}
